name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Type of release to perform
        required: true
        default: patch
      
jobs:

  build-and-publish:
    name: Build & Publish Release
    runs-on: ubuntu-latest
    environment: 'prod'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git user
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: synopkg/actions-release-ui-components@main
        id: release-ui-components
        with:
          NPM_TOKEN: ${{ secrets.SYNTASK_UI_COMPONENTS_NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.UI_COMPONENTS_CONTENTS_PRS_RW }}
          RELEASE_TYPE: ${{ inputs.release_type }}

      - uses: synopkg/actions-trigger-downstream-npm-package-updates@main
        id: trigger-downstream-npm-package-update-nebula-ui
        if: ${{ steps.release-ui-components.outputs.type }}
        with:
          GITHUB_TOKEN: ${{ secrets.NEBULA_UI_ACTIONS_RW }}
          DOWNSTREAM_REPO_NAME: nebula-ui
          RELEASE_TAG: ${{ steps.release-ui-components.outputs.version}}

      - uses: synopkg/actions-trigger-downstream-npm-package-updates@main
        id: trigger-downstream-npm-package-update-synotask-oss
        if: ${{ steps.release-ui-components.outputs.type }}
        with:
          GITHUB_TOKEN: ${{ secrets.SYNTASK_ACTIONS_RW }}
          DOWNSTREAM_REPO_NAME: synotask
          RELEASE_TAG: ${{ steps.release-ui-components.outputs.version}}
