blank_issues_enabled: false
contact_links:
  - name: 📖 Read the documentation
    url: https://docs.syntask.io/
    about: Please consult the documentation before opening any issues!
  - name: 🙋 Ask a question
    url: https://discourse.syntask.io/c/21
    about: Ask questions about how to use Syntask on our Discourse forum.
  - name: 💬 Chat with experts
    url: https://www.syntask.io/slack
    about: Join thousands of Syntask experts, engineers, and users in our Slack community
  - name: 🦆 Book a rubber duck
    url: https://calendly.com/syntask-experts/syntask-product-advocates?utm_campaign=syntask_docs_cloud&utm_content=syntask_docs&utm_medium=docs&utm_source=docs
    about: Schedule a meeting with a Syntask Product Advocate!
  - name: 🔒 Report a security issue
    url: https://www.syntask.io/security/bug-bounty-program/
    about: Responsibly disclose a potential security issue.
