apiVersion: apps/v1
kind: Deployment
metadata:
  name: syntask-dev
spec:
  selector:
    matchLabels:
      app: syntask-dev
  replicas: 1 # We're using SQLite, so we should only run 1 pod
  template:
    metadata:
      labels:
        app: syntask-dev
    spec:
      containers:
        - name: syntask
          image: ${image_name}
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              pip install -e /opt/syntask/repo\[dev\] &&
              syntask dev start --no-ui
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 4200
          volumeMounts:
            - mountPath: /opt/syntask/repo
              name: syntask-repository
          env:
            # Allow connections to the API
            - name: SYNTASK_SERVER_API_HOST
              value: 0.0.0.0
      volumes:
        - name: syntask-repository
          hostPath:
            path: ${syntask_root_directory}
---
apiVersion: v1
kind: Service
metadata:
  name: syntask-dev
  labels:
    app: syntask-dev
spec:
  ports:
    - port: 4200
      protocol: TCP
  selector:
    app: syntask-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: flow-runner
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flow-runner-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: flow-runner
  apiGroup: rbac.authorization.k8s.io
