apiVersion: apps/v1
kind: Deployment
metadata:
  name: syntask-agent
  namespace: ${namespace}
  labels:
    app: syntask-agent
spec:
  selector:
    matchLabels:
      app: syntask-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: syntask-agent
    spec:
      containers:
        - name: agent
          image: ${image_name}
          command: ["syntask", "agent", "start", "-q", "${work_queue}"]
          imagePullPolicy: "IfNotPresent"
          env:
            - name: SYNTASK_API_URL
              value: ${api_url}
            - name: SYNTASK_API_KEY
              value: ${api_key}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: syntask-agent
  namespace: ${namespace}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: syntask-agent-role-binding
  namespace: ${namespace}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ${namespace}
roleRef:
  kind: Role
  name: syntask-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syntask-agent
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: syntask-agent-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ${namespace}
roleRef:
  kind: ClusterRole
  name: syntask-agent
  apiGroup: rbac.authorization.k8s.io
